version: "3.8"
services:
  frontend:
    build: ./docker/frontend
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    tty: true
    deploy:
      resources:
        limits:
          memory: 2g

  backend:
    build: ./docker/backend
    volumes:
      - ./backend:/var/www/
    ports:
      - '8000:8000'
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel_db
        MYSQL_USER: laravel_user
        MYSQL_PASSWORD: laravel_pass
    command:
        mysqld --default-authentication-plugin=mysql_native_password
    volumes:
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  nginx:
    image: nginx:1.21.1
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
    tty: true
